@url = http://localhost:8080/api/

### Notes
GET {{url}}/notes/1 HTTP/1.1

###

GET {{url}}/notes/note/2 HTTP/1.1

###

POST {{url}}/notes HTTP/1.1
Content-Type: application/json

{
  "noteId": 0,
  "jobId": 1,
  "content": "post test"
}

###

PUT {{url}}/notes/note/4
Content-Type: application/json

{
  "noteId": 4,
  "jobId": 1,
  "content": "put test"
}


###
DELETE {{url}}/notes/note/4


### Jobs

GET {{url}}/jobs HTTP/1.1

###

GET {{url}}/jobs/1 HTTP/1.1

###


POST {{url}}/jobs HTTP/1.1
Content-Type: application/json

{
  "jobId": 0,
  "title": "post test",
  "description": "testing post",
  "jobStatus": "APPLIED",
  "url": "fakeurl.com",
  "notes": null
}

###

PUT {{url}}/jobs/4 HTTP/1.1
Content-Type: application/json

{
  "jobId": 4,
  "title": "put test",
  "description": "testing put",
  "jobStatus": "APPLIED",
  "url": "fakeurl.com",
  "notes": null
}

###
DELETE {{url}}/jobs/4